# Assignment 2: Scalability of Support Vector Machines
## Miles Nordwall, Nathan Nail

In [2]:
import numpy as np

### Task #1 Implement LinearSVC
doesn't work yet, need to finish task 2 so i can test the implementation
- [ ] missing weight update rule
- [ ] there are a bunch of todos just go through those

In [4]:
class LinearSVC(object):
    """
    Linear Support Vector Classifier
    Params: 
    eta (float) : Learning rate (between 0.0 and 1.0)
    n_iter (int) : Number of passes over the training dataset.
    random_state (int) : Random number generator seed for random weight initialization.

    Attrs:
    w_ (1d-array) : Weights after fitting with bias absorbed at X[0].
    losses_ (list) : Hinge Loss with L2-regularization loss function values in each epoch.
    """
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        self.w_ = []
        self.rand_gen = []
        self.w_initialized = False

    def fit(self, X, y, C=1.0):
        """
        Fitting Training Data
        Params:
        X {array-like}, shape = [n_examples, n_features]
        Training vectors, where n_examples is the number of examples and n_features is the number of features.
        y (array-like) ,shape = [n_examples]
        Target values.
        C {float} = regularization hyperparameter 

        Returns:
        self : Instance of LinearSVC
        """
        self.w_ = []
        self.losses_ = []

        X = self._initialize_weights(X,X.shape[1])

        c_n = np.ceil(C /n)
        for _ in range(self.n_iter):
            for xi, target in zip(X, y):
                
                
                loss = Li * c_n + (0.5 * (self.w_.shape[0])^2)
                self.losses_.append(self._update_weights(xi, target))
        
        
        return self
        

    
    def _initialize_weights(self, X, m):
        """Initialize weights to small random numbers"""
        n = X.shape[0] 
        x_0 = np.ones((n,-1)) #TODO2 does making x_0 all -1 fix the TODO1?
        X = np.hstack((x_0,X))
        
        self.rand_gen = np.random.RandomState(self.random_state)
        self.w_ = self.rand_gen.normal(loc=0.0, scale=0.01,
                                  size=1 + m) #m + 1 to account for the
                                              #absorbed bias
        self.w_initialized = True
        return X
        

    def _update_weights(self, xi, y):
        """Apply linear svc learning rule to update the weights"""
        output = self.activation(self.net_input(xi),target=y)

        #TODO do either QP or gradient descent to get error (prof mentioned QP!)
        #error = (y - output)

        self.w_  += self.eta * 2.0 * xi #* (error) TODO what the new update rule? 
        loss = output * c_n + (0.5 * (self.w_.shape[0])^2)
        return loss

    def net_input(self, X): #TODO1 the net_input for svc is w^Tx-b right? unabsorb b?
        """Calculate net input"""
        return np.dot(X, self.w_)

    def activation(self, y_hat,target):
        """Compute Hinge Loss"""
        return np.max(0, 1 - (target*y_hat))

    def predict(self, X):
        """Return class label after unit step"""
        n = X.shape[0]
        m = X.shape[1] #number of features in dataset
        x_0 = np.ones((n,1))
        X = np.hstack((x_0,X))

        #TODO should this really be 0.5?? or does the qp part go here?
        return np.where(self.activation(self.net_input(X)) >= 0.5, 1, -1)
    
        

### Task #2 make_classification function
$$\bar{a}^T \bar{x} = b$$
$$\{ \bar{x} \in \mathbb{R}^d | \bar{a}^T \bar{x} = b\}$$
$$\text{where } b=0$$

In [6]:
def make_classification(d,n, u=100,seed=1):
    """
    Generates a set of linearly seperable data
    based on a random seperation hyperplane
    d (int) : dimension of set of points
    """
    rand_gen = np.random.RandomState(seed)
    #generate random vector a s.t ||a||=d
    a = rand_gen.random(size=d) #TODO values are between [0-1] btw, is that okay?
    
    #randomly select n samples in range of [-u,u] in each dimension using a gaussian
    x = []
    for i in range(n):
        x_gauss = rand_gen.normal(scale=u,size=d)
        x.append(x_gauss)
    X = np.array(x)
    #give each xi a label yi 
    y = []
    for j in range(n):
        if a.T.dot(X[j]) < 0: #is this correct?
            yi = -1
        else:
            yi = 1
        y.append(yi)
    Y = np.array(y)

    #TODO make the first 70% training, and the last 30% test

    print(a)
    print(X)
    print(a.T.dot(X))
    print(Y)
    

make_classification(d=3,n=3,seed=1)

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[[ -80.21728386  -44.88778077 -110.5935076 ]
 [-165.45154524 -236.34686048  113.53453479]
 [-101.70141365   63.73618141  -85.99066067]]
[-152.64280512 -188.95833506   35.65194485]
[-1 -1  1]
